python test.py  --image  datasets/input/1.png --mask  datasets/mask/1.png  --output  datasets/output/1.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/2.png --mask  datasets/mask/2.png  --output  datasets/output/2.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/3.png --mask  datasets/mask/3.png  --output  datasets/output/3.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/4.png --mask  datasets/mask/4.png  --output  datasets/output/4.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/5.png --mask  datasets/mask/5.png  --output  datasets/output/5.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/6.png --mask  datasets/mask/6.png  --output  datasets/output/6.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/7.png --mask  datasets/mask/7.png  --output  datasets/output/7.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/8.png --mask  datasets/mask/8.png  --output  datasets/output/8.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/9.png --mask  datasets/mask/9.png  --output  datasets/output/9.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/10.png --mask  datasets/mask/10.png  --output  datasets/output/10.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/11.png --mask  datasets/mask/11.png  --output  datasets/output/11.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/12.png --mask  datasets/mask/12.png  --output  datasets/output/12.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/13.png --mask  datasets/mask/13.png  --output  datasets/output/13.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/14.png --mask  datasets/mask/14.png  --output  datasets/output/14.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/15.png --mask  datasets/mask/15.png  --output  datasets/output/15.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/16.png --mask  datasets/mask/16.png  --output  datasets/output/16.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/17.png --mask  datasets/mask/17.png  --output  datasets/output/17.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/18.png --mask  datasets/mask/18.png  --output  datasets/output/18.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/19.png --mask  datasets/mask/19.png  --output  datasets/output/19.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/20.png --mask  datasets/mask/20.png  --output  datasets/output/20.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/21.png --mask  datasets/mask/21.png  --output  datasets/output/21.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/22.png --mask  datasets/mask/22.png  --output  datasets/output/22.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/23.png --mask  datasets/mask/23.png  --output  datasets/output/23.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/24.png --mask  datasets/mask/24.png  --output  datasets/output/24.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/25.png --mask  datasets/mask/25.png  --output  datasets/output/25.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/26.png --mask  datasets/mask/26.png  --output  datasets/output/26.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/27.png --mask  datasets/mask/27.png  --output  datasets/output/27.png  --checkpoint_dir vis131 
python test.py  --image  datasets/input/28.png --mask  datasets/mask/28.png  --output  datasets/output/28.png  --checkpoint_dir vis131
 
python test.py  --image  datasets/input/1.png --mask  datasets/mask/1.png  --output  datasets/output/111.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/2.png --mask  datasets/mask/2.png  --output  datasets/output/112.png  --checkpoint_dir places2
python test.py  --image  datasets/input/3.png --mask  datasets/mask/3.png  --output  datasets/output/113.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/4.png --mask  datasets/mask/4.png  --output  datasets/output/114.png  --checkpoint_dir places2
python test.py  --image  datasets/input/5.png --mask  datasets/mask/5.png  --output  datasets/output/115.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/6.png --mask  datasets/mask/6.png  --output  datasets/output/116.png  --checkpoint_dir places2
python test.py  --image  datasets/input/7.png --mask  datasets/mask/7.png  --output  datasets/output/117.png  --checkpoint_dir places2
python test.py  --image  datasets/input/8.png --mask  datasets/mask/8.png  --output  datasets/output/118.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/9.png --mask  datasets/mask/9.png  --output  datasets/output/119.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/10.png --mask  datasets/mask/10.png  --output  datasets/output/1110.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/11.png --mask  datasets/mask/11.png  --output  datasets/output/1111.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/12.png --mask  datasets/mask/12.png  --output  datasets/output/1112.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/13.png --mask  datasets/mask/13.png  --output  datasets/output/1113.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/14.png --mask  datasets/mask/14.png  --output  datasets/output/1114.png  --checkpoint_dir places2
python test.py  --image  datasets/input/15.png --mask  datasets/mask/15.png  --output  datasets/output/1115.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/16.png --mask  datasets/mask/16.png  --output  datasets/output/1116.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/17.png --mask  datasets/mask/17.png  --output  datasets/output/1117.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/18.png --mask  datasets/mask/18.png  --output  datasets/output/1118.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/19.png --mask  datasets/mask/19.png  --output  datasets/output/1119.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/20.png --mask  datasets/mask/20.png  --output  datasets/output/1120.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/21.png --mask  datasets/mask/21.png  --output  datasets/output/1121.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/22.png --mask  datasets/mask/22.png  --output  datasets/output/1122.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/23.png --mask  datasets/mask/23.png  --output  datasets/output/1123.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/24.png --mask  datasets/mask/24.png  --output  datasets/output/1124.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/25.png --mask  datasets/mask/25.png  --output  datasets/output/1125.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/26.png --mask  datasets/mask/26.png  --output  datasets/output/1126.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/27.png --mask  datasets/mask/27.png  --output  datasets/output/1127.png  --checkpoint_dir places2 
python test.py  --image  datasets/input/28.png --mask  datasets/mask/28.png  --output  datasets/output/1128.png  --checkpoint_dir places2